server:
  port: 8085
spring:
  #配置静态资源
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/
  #配置数据库
  datasource:
    # url: jdbc:oracle:thin:@127.0.0.1:1521:xsteam
    # username: sa
    # password: Db877350
    # driver-class-name: oracle.jdbc.OracleDriver
    # url: jdbc:sqlserver://10.3.16.3:1433;SelectMethod=cursor;DatabaseName=jimureport
    # username: sa
    # password: Db877350
    # driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: {{url}}
    username: {{username}}
    password: {{password}}
    driver-class-name: {{driver-class-name}}
    # url: jdbc:mysql://${MYSQL-HOST:127.0.0.1}:${MYSQL-PORT:3306}/${MYSQL-DB:jimureport}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    # username: root
    # password: db877350
    # driver-class-name: com.mysql.cj.jdbc.Driver
#Minidao配置
minidao :
  base-package: org.jeecg.modules.jmreport.*
#JimuReport[上传配置]
jeecg :
  # local|minio|alioss
  uploadType: local
  # local
  path :
    #文件路径
    upload: /opt/upload
  # alioss
  oss:
    endpoint: ??
    accessKey: ??
    secretKey: ??
    bucketName: jimureport
  # minio
  minio:
    minio_url: http://minio.jeecg.com
    minio_name: ??
    minio_pass: ??
    bucketName: ??
#输出sql日志
logging:
  level:
    org.jeecg.modules.jmreport : info
